Code rechtstreeks in workflow geplaatst
Niet meer nodig om te verbinden met de server om het script aan te passen

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -19,4 +19,19 @@ jobs:
 
       - name: Execute deployment script
         run: |
-          /home/selab2/deploy.sh
+          APP_DIR="/home/selab2/dwengo"
+          DOCKER_COMPOSE_FILE="deploy-docker-compose.yml"
+
+          echo "Pulling latest code..."
+          cd $APP_DIR
+          git checkout main
+          git pull --force git@github.com:SELab-2/Dwengo-5.git || { echo "Git pull failed"; exit 1; }
+
+          cd $APP_DIR
+          docker-compose -f $DOCKER_COMPOSE_FILE down -v
+
+          echo "Building and deploying with Docker Compose..."
+          cd $APP_DIR
+          docker-compose -f $DOCKER_COMPOSE_FILE up --build -d || { echo "Docker Compose failed"; exit 1; }
+
+          echo "Deployment complete!"
